### ISSUE TITLE
Empty local variables + (theme) contexts like dark & saturated

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1087]
The intent of local variables is that they remain empty, so they always work at the :root level. However in some components, such as pfe-tabs, we use these variables to reset colors in dark or saturated contexts, for example, currently in pfe-tab.scss we have:

```scss
 :host([on="dark"][pfe-variant="earth"]) {
  --pfe-tabs--Color: #{pfe-var(text--on-dark)};
}
```

whereas if we instead redefined the original CSS properties such as border and color, and then set the value using the pfe-local function with the $fallback argument, this would preserve the empty local variable as a theming hook, while still setting the correct color for that context.

```scss
:host([on="dark"][pfe-variant="earth"]) {
  .pfe-tab * {
    color: pfe-local(Color, $fallback: pfe-var(text--muted--on-dark));
  }
}
```

The downside of this approach is that it makes theming the component a bit more tedious, because you have to redefine complex selectors, especially when state or light DOM is involved. 

However if we leave it as-is, folks wanting to redefine the text color of tabs in a dark context would be forced to figure out that they must use the `pfe-tab` selector (note that the component is pfe-tabs, so this is not intuitive). Even `!important` doesn't work with `:root`. 

```scss
pfe-tab{
--pfe-tabs--Color: pink;
}
```

Note that currently the pfe-cta component prints the following CSS  (which redefines all local vars)for each instance of the priority attributes, variant attributes, theme context attributes, states, and color attributes.
```
:host([pfe-priority="secondary"][pfe-variant="wind"]) {
  --pfe-cta--BackgroundColor: transparent;
  --pfe-cta--BorderColor: var(--pfe-theme--color--surface--border, #d2d2d2);
  --pfe-cta--Color: var(--pfe-broadcasted--link, #06c);
  --pfe-cta--FontWeight: var(--pfe-theme--font-weight--normal, 500);
  --pfe-cta--BackgroundColor--hover: var(--pfe-theme--color--surface--border--lightest, #f5f5f5);
  --pfe-cta--BorderColor--hover: var(--pfe-theme--color--surface--border, #d2d2d2);
  --pfe-cta--Color--hover: var(--pfe-theme--color--link--hover, #004080);
  --pfe-cta--TextDecoration--hover: var(--pfe-theme--link-decoration--hover, underline);
  --pfe-cta--Color--focus: var(--pfe-theme--color--link--hover, #004080);
  --pfe-cta--BorderColor--focus: var(--pfe-theme--color--surface--border, #d2d2d2);
  --pfe-cta__inner--BorderColor--focus: var(--pfe-cta--BorderColor--focus, transparent);
}
```
this means that redefined local vars on the :root` have little effect, 
<img src="https://user-images.githubusercontent.com/456863/92620509-bb4fc100-f290-11ea-85d1-a11cd609ca64.png" width="300" >

but if you change the selector to `pfe-cta` then you can override all instances of the CTA.
<img src="https://user-images.githubusercontent.com/456863/92620445-a6732d80-f290-11ea-9cd5-b7e54a72c27d.png" width="300" >

Whatever we decide, I'd like to make sure it's documented, and consistent across components.

**Comment by castastrophe** [comment]
Okay let's say we have `<pfe-cta pfe-priority="secondary" pfe-color="accent" on="dark">`;
  - `[pfe-priority="secondary"][pfe-color="accent"]` -- these are both added by the author
  - `[on="dark"]` -- this is added by the base class (pfelement) automatically

In the stylesheet for pfe-cta, I have this map:
```
$secondary-accent-dark: (
    BackgroundColor: transparent,
    BorderColor: pfe-var(ui-accent--on-dark),
    Color: pfe-var(ui-accent--on-dark),
  
    BackgroundColor--hover: pfe-var(ui-accent--on-dark),
    BorderColor--hover: pfe-var(ui-accent--on-dark),
    Color--hover: pfe-var(ui-accent--text),
  
    BackgroundColor--focus: pfe-var(surface--lighter),
    BorderColor--focus: pfe-var(ui-accent--on-dark),
    Color--focus: pfe-var(ui-accent--on-dark),
  
    inner: (BorderColor--focus: pfe-var(ui-accent--on-dark)),
  );
```

And it is being invoked here:
```
:host([pfe-priority="secondary"][pfe-color="accent"][on="dark"]) {
  @include pfe-print-local($secondary-accent-dark);
}
```

This is the compiled output:
```
:host([pfe-priority="secondary"][pfe-color="accent"][on="dark"]) {
  --pfe-cta--BackgroundColor: transparent;
  --pfe-cta--BorderColor: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta--Color: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta--BackgroundColor--hover: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta--BorderColor--hover: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta--Color--hover: var(--pfe-theme--color--ui-accent--text, #fff);
  --pfe-cta--BackgroundColor--focus: var(--pfe-theme--color--surface--lighter, #f0f0f0);
  --pfe-cta--BorderColor--focus: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta--Color--focus: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
  --pfe-cta__inner--BorderColor--focus: var(--pfe-theme--color--ui-accent--on-dark, #7dc3e8);
}
```
^ This means it's harder for me as an author be create global customizations on my page.

For an author to be able to customize this component, we would need to use this approach instead:
```
$hold: $LOCAL-VARIABLES;
$LOCAL-VARIABLES: $secondary-accent-dark;

:host([pfe-priority="secondary"][pfe-color="accent"][on="dark"]) {
  background-color: pfe-local(BackgroundColor);
  border-color: pfe-local(BorderColor);
  ::slotted(*) {
    color: pfe-local(Color);
  }
}

:host([pfe-priority="secondary"][pfe-color="accent"][on="dark"]:hover) {
  --pfe-cta--BackgroundColor: pfe-local(BackgroundColor--hover);
  --pfe-cta--BorderColor: pfe-local(BorderColor--hover);
  --pfe-cta--Color: pfe-local(Color--hover);
}

:host([pfe-priority="secondary"][pfe-color="accent"][on="dark"]:focus) {
  --pfe-cta--BackgroundColor: pfe-local(BackgroundColor--focus);
  --pfe-cta--BorderColor: pfe-local(BorderColor--focus);
  --pfe-cta--Color: pfe-local(Color--focus);
}

$LOCAL-VARIABLES: $hold;
```

Now this means that `--pfe-cta--BackgroundColor` set on root will influence CTAs of every variation.  Is this desirable?  I can't speak to that.  I kind of think it's not because I don't want a primary and a secondary CTA to get the same global style changes.

I know it's verbose and a bit kuku-bananas but wouldn't I need something like `--pfe-cta--BackgroundColor--secondary--accent--on-dark` for that kind of granular styling?

**Comment by castastrophe** [comment]
Another way to approach this conceptually:

```scss
//-- Contextual update - this sets the color to be featured
:host([pfe-color="accent"]) {
  --pfe-cta--accent: pfe-var(ui-accent);
  --pfe-cta--accent-text: pfe-var(ui-accent--text);
}

:host([pfe-color="accent"][on="dark"]) {
  --pfe-cta--accent: pfe-var(ui-accent--on-dark);
  --pfe-cta--accent-text: pfe-var(ui-accent--text--on-dark);
}

:host([pfe-color="accent"][on="saturated"]) {
  --pfe-cta--accent: pfe-var(ui-accent--on-saturated);
  --pfe-cta--accent-text: pfe-var(ui-accent--text--on-saturated);
}

//-- The variant determines to which properties the values are applied
:host([pfe-priority="secondary"]) {
  background-color: transparent;
  border-color: pfe-local(accent);
  ::slotted(*) {
    color: pfe-local(accent);
  }
}

//-- State, update the properties that change
:host([pfe-priority="secondary"]:hover) {
  background-color: pfe-local(accent);
  ::slotted(*) {
    color: pfe-local(accent-text);
  }
}

:host([pfe-priority="secondary"]:focus) {
  background-color: pfe-var(surface--lighter);
  .pfe-cta__inner {
    border-color: pfe-local(accent);
  }
}
```

**Comment by starryeyez024** [comment]
> Now this means that --pfe-cta--BackgroundColor set on root will influence CTAs of every variation. Is this desirable? I can't speak to that. I kind of think it's not because I don't want a primary and a secondary CTA to get the same global style changes.

I would agree that it's undesirable; since the styles are so different (button vs non-button).


> For the user, this would mean if you use pfe-priority="secondary" and you don't add pfe-color="accent", you can set --pfe-cta--accent on :root and it will influence your secondary and primary CTAs in different but perhaps more obvious ways.

I'm slightly confused on this one; it seems like the user *would* have to put the attribute `pfe-color="accent"` on the CTA for it to invoke usage of the variables `  --pfe-cta--accent` or `--pfe-cta--accent-text`. But after they did, it sounds like your point is that they could change the value of those accent vars and it would only impact the CTAs with that attribute

**Comment by starryeyez024** [comment]
Can we break variables down into 2 groups?

### State 

- State interactions are triggered by the site visitor
- Page-builder-devs should be able to control state-vars AND  original variables, independently
- Create separate vars for these, that show up in the debug mixin print-out and in the console
- In this instance, it would be ok to redefine the value of a local variable, because its value is another local variable which we expect page-builder-devs to use.

```css
:host(:hover){
  --pfe-tabs--Color: var(--pfe-tabs--Color--hover);
```


### Everything else
These items are choices made by the dev building the page

- **Context (on) attribute, i.e.  `<pfe-cta on="dark">`**
    - Page-builder-dev  should be able to override vars even if component is in a dark context
- **Color attribute, i.e.  `<pfe-cta pfe-color="accent">`**
    - Affects color-specifically, but its not clear where or how
        - These could have their own set of variables, like 
            - `--pfe-cta--accent`
            - `--pfe-cta--complement`
    - But, Page-builder-devs should still be able to override vars like margin or padding, even if they are leveraging an attribute that changes colors 
- **Variant attribute, i.e.  `<pfe-tabs pfe-variant="earth">`**
    - Affects multiple properties such as padding, border, color, etc.
    - Support local var overrides
    - Page-builder-dev  should be able to override vars like color, even if they are leveraging an attribute like pfe-variant=earth on tabs, because that alters padding, borders, margins, etc
- **Priority attribute  i.e.  `<pfe-cta pfe-priority="primary">`**
    - Affects multiple properties such as padding, border, color, etc.
    - Page-builder-dev  should be able to override vars like color, but may need to do so per priority type


### Ways to tackle the implementation

#### Option 1, build selector once, list all possible vars that control color, then you only need to build the host+attributes selector further on down in the file?

```css
:host(){
    pfe-tab > *
    color: pfe-local(Color);
    --pfe-tabs--Color--on-dark: pfe-local(Color, $fallback: lt-blue);
    --pfe-tabs--Color--on-saturated: pfe-local(Color, $fallback: white);

:host([on="dark"]){
    color: pfe-local(Color--on-dark)

:host([on="saturated"]){
    color: pfe-local(Color--on-saturated)
```
 
#### Option 2, build selector again & again, redefine property each time, leverage $fallback

```css
:host(){
     pfe-tab > *
        color: pfe-local(Color)

:host([on="dark"]){
    pfe-tab > *
        color: pfe-local(Color, $fallback: #760 
```

#### Option 3 for pfe-color (not mutually exclusive to the other two options)

Per Cassondra's suggestion, add an abstract variable with the name of the color (accent or complement) 

````css
:host([pfe-color="accent"]) {
  --pfe-cta--accent: pfe-var(ui-accent);
  --pfe-cta--accent-text: pfe-var(ui-accent--text);
  --pfe-cta--accent--hover: pfe-var(ui-accent--hover);
  --pfe-cta--accent-text--hover: pfe-var(ui-accent--text--hover);
}
````
