### ISSUE TITLE
[fix] pfe-band + pfe-card | Context custom property not picking up

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1252]
The `--theme` or `--context` custom property should set the context value for the `on` attribute.  This code for example:

```css
.custom-background {
    background-color: #123D99;
    --theme: saturated;
}
```

Should update the component to use the `on=saturated` context but instead it is picking up `on=light` because of this code:

```css
:host([color=base]) {
    --pfe-card--BackgroundColor: var(--pfe-theme--color--surface--base, #f0f0f0);
    --pfe-card--context: var(--pfe-theme--color--surface--base--context, light);
}
```
<img width="735" alt="Screen Shot 2021-01-04 at 2 22 11 PM" src="https://user-images.githubusercontent.com/1840295/103571288-9b27bb80-4e98-11eb-9935-ef2a65b76f1d.png">

### Impacted component(s)

- pfe-card
- pfe-band

## Related issues

- (#831) update pfe-band to use transparent as the default with no theme value defaulted.
