### ISSUE TITLE
pfe-sass typography mixin does not apply extra "base" styles uniformly

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1384]
## Description of the issue

 
In pfe-typography-classes.CSS, the modifier styles:
 - Titles ship with all the styles (line-height, margin, font-weight) by default
 - Text ships with font size only, because the theory is that it's inheriting the default line-height, font-weight and font-family from the body tag. If you want to include these properties, there's an extra argument you can invoke in the mixin. 
 - However the mixin *should* allow you to opt in or out, if you are calling it in your own project., regardless of title vs. text

## Text

```scss
.foo {
  @extend %pfe-text--lg;
}
.bar {
 @include pfe-typography(lg, $type: "text"); 
}
.baz {
 @include pfe-typography(lg, $type: "text", $base: true); 
}

```
 

```css
.foo {
  font-size: 18px;
  font-size: var(--pf-c-text--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
}

.foo:not(:last-child):not(:empty) {
  margin-bottom: 8px;
  margin-bottom: var(--pfe-theme--content-spacer--body--sm, 8px);
}

.bar {
  font-size: 18px;
  font-size: var(--pf-c-text--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
}

.bar:not(:last-child):not(:empty) {
  margin-bottom: 8px;
  margin-bottom: var(--pfe-theme--content-spacer--body--sm, 8px);
}

.baz {
  font-size: 18px;
  font-size: var(--pf-c-text--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
  font-family: "Red Hat Text", "RedHatText", "Overpass", Overpass, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family, "Red Hat Text", "RedHatText", "Overpass", Overpass, Arial, sans-serif);
  line-height: 1.5;
  line-height: var(--pfe-theme--line-height, 1.5);
  font-weight: 400;
  font-weight: var(--pfe-theme--font-weight--normal, 400);
}

.baz:not(:last-child):not(:empty) {
  margin-bottom: 8px;
  margin-bottom: var(--pfe-theme--content-spacer--body--sm, 8px);
}
```

## Titles

the opposite is true here, you should be able to opt out of the extra properties if desired, via that same argument set to false:

```scss
.foo {
  @extend %pfe-title--lg;
}
.bar {
 @include pfe-typography(lg, $type: "title"); 
}
.baz {
 @include pfe-typography(lg, $type: "title", $base: false); 
}
```

```css
.foo {
  font-family: "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif);
  font-size: 18px;
  font-size: var(--pf-c-title--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
  line-height: 1.5;
  line-height: var(--pfe-theme--line-height, 1.5);
  font-weight: 400;
  font-weight: var(--pfe-theme--font-weight--normal, 400);
}

.foo:not(:last-child) {
  margin-bottom: 16px;
  margin-bottom: var(--pfe-theme--content-spacer--heading--sm, 16px);
}

.bar {
  font-family: "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif);
  font-size: 18px;
  font-size: var(--pf-c-title--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
  line-height: 1.5;
  line-height: var(--pfe-theme--line-height, 1.5);
  font-weight: 400;
  font-weight: var(--pfe-theme--font-weight--normal, 400);
}

.bar:not(:last-child) {
  margin-bottom: 16px;
  margin-bottom: var(--pfe-theme--content-spacer--heading--sm, 16px);
}

.baz {
  font-family: "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "Red Hat Display", "RedHatDisplay", "Overpass", Overpass, Arial, sans-serif);
  font-size: 18px;
  font-size: var(--pf-c-title--m-lg--FontSize, var(--pf-global--FontSize--lg, 18px));
  line-height: 1.5;  /* This shouldn't be here */
  line-height: var(--pfe-theme--line-height, 1.5); /* This shouldn't be here */
  font-weight: 400; /* This shouldn't be here */
  font-weight: var(--pfe-theme--font-weight--normal, 400); /* This shouldn't be here */
}

.baz:not(:last-child) {
  margin-bottom: 16px; /* This shouldn't be here */
  margin-bottom: var(--pfe-theme--content-spacer--heading--sm, 16px); /* This shouldn't be here */
}
```

### Impacted component(s)

- pfe-sass

### Steps to reproduce

3. Scroll to '....'
4. Check console
5. See error

## Related issues

- (#100) Description
