### ISSUE TITLE
[fix] Container sass placeholder has incorrect variable for spacing

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#1522]
This placeholder in the `pfe-sass/extends/_extends.scss` file has the padding property using the `container-spacer` var, and it should use `container-padding`.

```scss
/// Set up a container element
%container {
  position: relative;
  display: block;
  width: 100%;
  padding: pfe-var(container-spacer);
}
```
