### ISSUE TITLE
[ci] Automerge action update

### ISSUE THREAD

**Issue by castastrophe** [patternfly/patternfly-elements#1615]
Can automerge be handled using gh cli instead?
```
steps:
  - name: Enable auto-merge for new PRs
    run: gh pr merge --auto --merge "$PR_URL"
    env:
      PR_URL: ${{ github.event.pull_request.html_url }}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
