### ISSUE TITLE
PFE-Band should have fallback styles so JS isn't required for any sort of layout

### ISSUE THREAD

**Issue by wesruv** [patternfly/patternfly-elements#1749]
## Description of the issue
PFE-band requires JS to be enabled to provide any layout, which isn't great. We could provide light DOM styles as a fallback so things didn't look gross.

I made a quick attempt at fallback styles:
```css
pfe-band:not([pfelement]) {
  box-sizing: content-box;
  width: auto;
  max-width: 1136px;
  max-width: var(--pfe-band--Width, 1136px);
  margin-left: auto;
  margin-right: auto;
  padding: 32px 16px;
  padding: var(--pfe-band--Padding,var(--pfe-band--Padding--vertical,calc(var(--pfe-theme--container-spacer,16px) * 4)) var(--pfe-band--Padding--horizontal,calc(var(--pfe-theme--container-spacer,16px) * 1)));
}
```

I think those styles do something similar to what pfe-band's styles do, but I didn't look too hard, so my styles should be double checked.

### Impacted component(s)

- pfe-band

### Steps to reproduce

1. Go to a page with pfe-band
2. Disable JS
3. It shouldn't look like there isn't any styles and everything is broken, but it do.

### Screenshots
![pfe-band-no-js](https://user-images.githubusercontent.com/5607236/129222601-8474450f-d104-402a-9aa6-ccd4c9289389.png)
