### ISSUE TITLE
pfe-band issues / suggestions

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#310]
### 1. height of children in body

```css
.pfe-band__body {
    display: flex;
    flex-flow: column nowrap;
    align-items: flex-start; // this prop causes this children not to fill the height of the row
}
```

![card-height](https://user-images.githubusercontent.com/456863/51810149-27c0ac80-2274-11e9-8179-338227d9e788.gif)

### 2. Inline styles in the demo 

Demo page, orange example "Aside: left body top" has inline styles causing overlap
 `style="height: -webkit-fill-available;"`

![overlap](https://user-images.githubusercontent.com/456863/51811512-44acae00-227b-11e9-9786-5b93b6a0504e.jpg)

### 3. Formatting of grid props for readability

Not a bug, but a suggestion. Can we format the CSS so that its easier to see what the regions are?
```
--pfe-band--gridTemplateArea_desktop: 
          "header  header" 
          "body    aside" 
          "footer  footer";
```

### 4. Band should set max-width instead of width

To avoid the band breaking out of any other container

![image](https://user-images.githubusercontent.com/456863/53104815-0dd65a80-34fe-11e9-9f2e-d2b5eaae7081.png)
