### ISSUE TITLE
Padding & Spacer variables

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#675]
We need clear definitions around when to use which one of these variables:

```scss
  container-spacer:              16px,
  container-padding:             16px,
  content-spacer:                  24px,
```

There seems to be some mix`n`match in some components but my general understanding is:

- Container spacer is used to align UI items in components, like the chevron in an accordion header
- Container padding is used between the edges of containers and the content they hold
- Content spacer is used between sections within containers, like card header & card body, or band body & band footer.

Can anyone either tell me if these assumptions are right or wrong, and let's add that to the docs and clean up some of the outliers, like for example this is in the _extends.scss:
```scss

%container {
    position: relative;
    display: block;
    width: 100%;
    padding: #{pfe-var(container-spacer)};
}
```
(and I think that should be container-padding). Thanks!
