### ISSUE TITLE
Replace contents of pfe-base.css with _globals.scss from PF core

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#899]
@patternfly/patternfly/base/_globals.scss is 1:1 with the pfe-base file, it should just extend from the sass partial.

**Comment by starryeyez024** [comment]
I looked at the two files side by side and they are not 1:1 (anymore). We could keep this issue open and review & discuss the differences with UXD to try to bring them back into parity. We would need another round of typography updates, so that PFE uses PF core variables with the pf-global prefix.

Example snippet from `@patternfly/patternfly/base/_globals.scss`

```css
  body {
    font-family: var(--pf-global--FontFamily--sans-serif);
    font-size: var(--pf-global--FontSize--md);
    font-weight: var(--pf-global--FontWeight--normal);
    line-height: var(--pf-global--LineHeight--md);
    text-align: left;
    background-color: var(--pf-global--BackgroundColor--100);
  }

  // Links styles

  a {
    font-weight: var(--pf-global--link--FontWeight);
    color: var(--pf-global--link--Color);
    text-decoration: var(--pf-global--link--TextDecoration);

    &:hover {
      --pf-global--link--Color: var(--pf-global--link--Color--hover);
      --pf-global--link--TextDecoration: var(--pf-global--link--TextDecoration--hover);
    }
  }
```
