### ISSUE TITLE
Add typography classes to pfe-styles

### ISSUE THREAD

**Issue by starryeyez024** [patternfly/patternfly-elements#936]
- the typography classes from the [redhat-theme](https://static.redhat.com/libs/redhat/redhat-theme/latest/advanced-theme.css) should live in pfe-styles, for example:

```css
.pfe-headline-xxl {
  font-family: "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif;
  font-family: var(--pfe-theme--font-family--heading, "RedHatDisplay", "Overpass", Overpass, Helvetica, Arial, sans-serif);
  font-size: calc(1.92  * 18px);
  font-size: var(--pfe-theme--font-size--xxl, calc(1.92  * var(--pfe-theme--base--heading-lg, 25px)));
  line-height: 1.2;
  line-height: var(--pfe-theme--line-height--xxl, 1.2);
  font-weight: 300;
  font-weight: var(--pfe-theme--font-weight--xxl, 300); }
```
