### ISSUE TITLE
surface--lighter var hex value does not match PatternFly hex value

### ISSUE THREAD

**Issue by kelsS** [patternfly/patternfly-elements#949]
## Description of the issue

`surface--lighter` var hex value does not match PatternFly hex value for the background color of dropdown list items when items are hovered, focused, or active.

The current hex value is rendering to be: `#ececec`

The hex color value for PatternFly is: 
`--pf-c-dropdown__menu-item--hover--BackgroundColor: #f0f0f0`

### Impacted component(s)

- `pfe-autocomplete`

### Steps to reproduce

1. Start PFE demo and go to http://localhost:8000/elements/pfe-autocomplete/demo/
2. Click on on autocomplete input and start typing search
3. Press the down arrow key to select a list item in the dropdown
4. Check devtools and see the hex value for the style block that is applied to the `ul` inside of `<pfe-search-droplist>`
   ```css
     ul li.active {
        background-color: #ececec;
        background-color: var(--pfe-theme--color--surface--lighter,#ececec);
     }
   ```

### Expected behavior

- Expected the hex value to be: `#f0f0f0` to match [PatternFly](https://www.patternfly.org/v4/documentation/react/components/dropdown#css-variables) var `--pf-c-dropdown__menu-item--hover--BackgroundColor` instead of `#ececec`
