### ISSUE TITLE
typo - double semi-colon at the end of style rule 

### ISSUE THREAD

**Issue by kelsS** [patternfly/patternfly-elements#950]
## Description of the issue

typo: double semi-colon (`;;`) at the end of style rule for `pfe-autocomplete` in file `pfe-search-droplist.scss` on line `55` for `ul li` styles.

### Impacted component(s)

- `pfe-autocomplete`
- [File location on GitHub](https://github.com/patternfly/patternfly-elements/blob/master/elements/pfe-autocomplete/src/pfe-search-droplist.scss)

### Steps to reproduce

1. Go to `/patternfly-elements/elements/pfe-autocomplete/src/pfe-search-droplist.scss`
2. Find line `55` or look for the following style block:
```css
  li {
      display: list-item;
      cursor: pointer;
      padding: 10px;
      margin: 0px; /*margin needs to be zero otherwise we have blind area on click*/
      &.active {
          background-color: #{pfe-color( surface--lighter )};;
      }
  }
```

### Expected behavior

Expected line to only have one semi-colon `;` to end the style rule.

## Related issues

- ( #949)
